# Generated by Django 5.1.3 on 2025-06-14 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('exigences', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DossierVisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_visa', models.CharField(choices=[('TOURISME', 'Tourisme'), ('AFFAIRES', 'Affaires')], max_length=20)),
                ('statut', models.CharField(choices=[('BR', 'Brouillon'), ('SO', 'Soumis'), ('VA', 'Validé')], default='BR', max_length=2)),
                ('documents', models.FileField(upload_to='dossiers/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='core.client')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='travel.paysdestination')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVousAmbassade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='travel.dossiervisa')),
            ],
        ),
    ]
