# Generated by Django 5.2 on 2025-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('consentement', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
