# Generated by Django 5.2 on 2025-06-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAideEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('domaine', models.CharField(max_length=100)),
                ('besoin', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.CharField(default='0000', max_length=4)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('kilometrage', models.PositiveIntegerField(default=0)),
                ('nb_places', models.PositiveIntegerField(default=0)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='vehicules/')),
                ('type', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion')], max_length=10)),
                ('carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique')], default='ESSENCE', max_length=10)),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUEL', 'Manuelle')], default='non-defini', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonAutoEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TERMINEE', 'Terminée')], max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='core.client')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons_donnee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pieces/', verbose_name='Photo de la pièce')),
                ('compatible_avec', models.ManyToManyField(related_name='pieces_compatibles', to='services.vehicule')),
            ],
        ),
    ]
