# Generated by Django 5.1.3 on 2025-06-14 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAutoEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TERMINEE', 'Terminée')], max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='core.client')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons_donnee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion')], max_length=10)),
                ('photo', models.ImageField(upload_to='vehicules/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
        migrations.AddField(
            model_name='piecedetachee',
            name='compatible_avec',
            field=models.ManyToManyField(related_name='pieces_compatibles', to='services.vehicule'),
        ),
    ]
