# Generated by Django 5.2 on 2025-06-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='annee',
            field=models.CharField(default='1999', max_length=4),
        ),
    ]
