# Generated by Django 5.2 on 2025-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_lessonautoecole_piecedetachee_vehicule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAideEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('domaine', models.CharField(max_length=100)),
                ('besoin', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='piecedetachee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/', verbose_name='Photo de la pièce'),
        ),
    ]
